### ISSUE TITLE
Dataset preprocessing

### ISSUE THREAD

**Issue by yuanqidu** [samgoldman97/ms-pred#6]
Dear authors,

Thanks for the amazing work! May I ask if the dataset preprocessing codes are included in the repo? I dived into the codes and didn't find one.

Thanks,
Yuanqi

**Comment by samgoldman97** [comment]
Hi Yuanqi, 
Thank you for the kind words and interest! You can find most of the preprocessing scripts in `data_scripts/` (as described in README). The GNPS dataset was extracted from the CANOPUS paper more or less in the format that we link to re-download. NIST was parsed as described [here](https://github.com/samgoldman97/nist-parser). Let me know if there's anything else you're looking for. 

Best,
Sam

**Comment by yuanqidu** [comment]
Thanks so much for your prompt response! Just another quick question, for GNPS, I believe you also filtered 1,500 Da and adduct types. Just double check if the downloaded GNPS from the link already got filtered or it was explicitly filtered out in the code?

Thanks again!

**Comment by samgoldman97** [comment]
Should already be filtered!

**Comment by yuanqidu** [comment]
Thanks!

**Comment by yuanqidu** [comment]
Dear Sam, sorry for bother you again, I downloaded NIST following this repo https://github.com/Roestlab/massformer, but your repo (https://github.com/samgoldman97/nist-parser) seems to read the data from the NIST SDF file, may I know how the SDF is obtained from the original source? 

Thanks again!

**Comment by samgoldman97** [comment]
Hi Yuanqi, 
If I recall correctly, the SDF was one of the files i was able to extract using the Massformer's instructions directly-- I don't recall taking any additional steps beyond what was described in MassFormer. I used a windows machine to extract it not currently accessible. If you're not able to do this, I would recommend parsing the MSP directly. 

Sam

**Comment by yuanqidu** [comment]
Thanks for your prompt reply! I will play with their code and see how to bridge the two!

**Comment by yuanqidu** [comment]
I managed to process from the MSP to obtain the data, just two quick questions: (1) for PRECURSOR M/Z, is this the mass for the parent molecule or parent molecule + ion mass? (2) is it possible to include [M-H]- as one adduct type? 

For the second question, I feel it is possible to just extend the list where it is used, correct me if I were wrong!

Thanks again for your help and great work!

**Comment by yuanqidu** [comment]
also spot one thing `ms-pred/src/ms_pred/common/chem_utils.py`, ion2mass, should it be minus the mass of hydrogen since its minus H2O together

`"[M-H2O+H]+": -ELEMENT_TO_MASS["O"] + ELEMENT_TO_MASS["H"] - ELECTRON_MASS,`
`"[M+H-H2O]+": -ELEMENT_TO_MASS["O"] + ELEMENT_TO_MASS["H"] - ELECTRON_MASS,`

**Comment by samgoldman97** [comment]
Thanks for the catch-- will leave this as is for now with a comment in the readme and make sure to fix as part of revision process (I don't want to mess up pre-trained models by shifting this now)

**Comment by yuanqidu** [comment]
Glad to help! Sorry if this question is missed: 

I managed to process from the MSP to obtain the data, just two quick questions: (1) for PRECURSOR M/Z, is this the mass for the parent molecule or parent molecule + ion mass? (2) is it possible to include [M-H]- as one adduct type?

For the second question, I feel it is possible to just extend the list where it is used, correct me if I were wrong!

Thanks again for your help and great work!

**Comment by samgoldman97** [comment]
No problem to help at all. Also, feel free to email me rather than going back and forth on this issue-- I'm happy to contribute in a more active guidance role or help you think through next steps, as we are not planning to actively develop new forward models outside of a simple extension of adding a few additional covariates into our model (instrument type + collision energy, etc.). 

Re. precursor M/Z, usually this refers to the observed mass over charge at the MS1 level, which is the parent molecule mass + ion mass. I would do a few manual checks for yourself (you can use the utility functions chem_utils if you already have the package `common.mass_from_smi(SMILES) + common.ion2mass[ADDUCT]`). One thing to look out for is that in some of these standards libraries like NIST, they give you _theoretical_ mass rather than observed mass with error. This is less relevant for forward prediction, but matters for something like learning to predict chem formula from spectra (https://www.nature.com/articles/s41592-023-01850-x). 

Lastly, regarding negative mode-- this will likely work if you want negative mode spectra as well. There may be some nuances to how molecules fragment, but since it's a learned model anyways it may not matter.

**Comment by yuanqidu** [comment]
Thanks so much for the detailed explanations! Yeah, I will send an email and happy to learn more from you!

**Comment by samgoldman97** [comment]
Corrected ion2mass in latest runs / pull for camera ready! Thanks again for flagging.
